version: '3'
services:
  unique-service:
    stdin_open: true
    tty: true
    command: ['nodemon']
    volumes:
      - ./app/controllers:/app/controllers
      - ./app/integration-test:/app/integration-test
      - ./app/lib:/app/lib
      - ./app/middleware:/app/middleware
      - ./app/migrations:/app/migrations
      - ./app/models:/app/models
      - ./app/routes:/app/routes
      - ./app/scripts:/app/scripts
      - ./app/validators:/app/validators
      # Don't mount the local copy of node_modules, for compatibility reasons
      - /app/node_modules
    ports:
      - '4000:4000'
      - '9229:9229'
