version: "3"
services:
  unique-service:
    image: ${DOCKERTAG:-node-service-sample}
    build:
      context: .
      args:
        NPM_TOKEN: ${NPM_TOKEN}
    environment:
      DB_PASSWORD:
      DB_HOST:
      DB_NAME:
      DB_USER:
      DB_DEBUG:
      RAMBLER_DRIVER:
      RAMBLER_PROTOCOL:
      RAMBLER_HOST: ${DB_HOST}
      RAMBLER_PORT:
      RAMBLER_USER: ${DB_USER}
      RAMBLER_PASSWORD: ${DB_PASSWORD}
      RAMBLER_DATABASE: ${DB_NAME}
      RAMBLER_DIRECTORY:
      RAMBLER_TABLE:
      SCHEMA_RAMBLER_USER:
      SCHEMA_RAMBLER_PASSWORD: ${DB_PASSWORD}
      SCHEMA_RAMBLER_DIRECTORY:
      SCHEMA_RAMBLER_TABLE:
      DB_ENG_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - pg
    ports:
      - "4000"
    command: ["npm", "run server"]
  pg:
    image: postgres:9.6.9
    ports:
      - "5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
